### ISSUE TITLE
[Enhancement]: Live Rover Pose Improvements

### ISSUE THREAD

**Issue by tariqksoliman** [NASA-AMMOS/MMGIS#485]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Describe the feature request

Note: Improve rover pose display, so rover image not reloaded on every position update. Support ability to control rover (image) opacity or turn it off. Don’t “de-select” draw object metadata when new pose update arrives.

- Wanted live updates. Adding points to one layer, but now going to track layer with current rover pose (‘now’ of rover). Updates at 1 Hz. Need to add and trim a point. This causes the rover image to be redrawn (flashes). Potential solution: put image in memory to reduce flash time OR new Layer API to modify an existing point.

- If you turn the rover image off, it comes back on after a second. Layer settings should be respected in Waypoint Kind Layers. Maybe make rover image respect transparency?

---

- [x] Feature overlay images should not flash when adding or removing features to a layer.
- [x] Adding or removing features from a layer should respect the existing overlay image visibility state.
- [x] Add ability to set overlay image transparency.
- [x] Do not deselect a draw object when any other layer gets updated.

**Comment by khalidadil** [comment]
hi Tariq, I'm noticing the following:
* keepLastN immediately following an updateVectorLayer no longer works. I've switched to the pattern where the keepLastN value is passed to the updateVectorLayer call instead, and that works.
* Uncertainty Ellipse state is reset on every layer update (new feature added)
* Opacity state is reset on every layer update (new feature added)

This video is using the ts-485 branch:
https://github.com/NASA-AMMOS/MMGIS/assets/2343076/e55b6097-3e61-4dfa-8272-a9b78bbad603

**Comment by khalidadil** [comment]
Separate, but I'm also seeing this error:
![Screenshot 2024-01-26 at 5 20 03 AM](https://github.com/NASA-AMMOS/MMGIS/assets/2343076/ae1f6253-82c7-4483-b33a-080d8581e21b)

It looks like this is the code, and for some reason it's accessing that layer at a string of "0" instead of an index of 0? I've attempted to capture what I'm seeing in this image:
<img width="1470" alt="Screenshot 2024-01-26 at 5 11 36 AM" src="https://github.com/NASA-AMMOS/MMGIS/assets/2343076/af2c2642-eb8c-44ed-a8f0-5b22697b2e34">

**Comment by khalidadil** [comment]
Also unrelated (and I can move this elsewhere), sometimes I'm having issues moving drawing features. See the following video using the ts-485 branch:
https://github.com/NASA-AMMOS/MMGIS/assets/2343076/9bdb9758-a7ca-43e1-abd6-95fa47a0652a

**Comment by tariqksoliman** [comment]
@khalidadil Thank you for investigating further issues; I'll starting working on them right now.

As for dragging drawn features, that functionality was in an adjacent PR and now in the development branch -- this ts-485 does not have that addition.

**Comment by tariqksoliman** [comment]
> keepLastN immediately following an updateVectorLayer no longer works. I've switched to the pattern where the keepLastN value is passed to the updateVectorLayer call instead, and that works.
Yes, keepLastN internally calls an update/make layer function that can sometimes race/conflict with updatevectorlayer. The new pattern is preferred now and should be a little more performant.

**Comment by tariqksoliman** [comment]
@khalidadil I've addressed the remaining issues too -- please give it another try. Thanks!

**Comment by khalidadil** [comment]
@tariqksoliman Still testing this, but noticing we're still getting flickering of the rover image. I'm not sure what can be done about this:
https://github.com/NASA-AMMOS/MMGIS/assets/2343076/7c30e4d3-3e8b-4985-8e25-1e846117a9e7

**Comment by khalidadil** [comment]
I'm also noticing that clicking the reset icon next to the "Layer Settings" text only resets the Opacity, not the "Composite Layers" settings. Is that the intended behavior?

**Comment by tariqksoliman** [comment]
Yes, that reset button was never meant for the composite layers too (though I suppose it could be).

I'll look into the flickering more.

**Comment by tariqksoliman** [comment]
@khalidadil Just pushed another change to address the flickering. Could you give it try again? Thanks!

**Comment by khalidadil** [comment]
@tariqksoliman This is looking great now! I can confirm the 3 layer settings for vector opacity, image overlay opacity, and ellipse toggle work as expected, and I'm not seeing flickering when the rover changes positions on the map. I need to bring this into an environment where I can test the memory issue again, but otherwise things are looking really good!

When clicking on the rover or the historical track features, I am seeing this error:
<img width="894" alt="Screenshot 2024-02-02 at 12 24 40 PM" src="https://github.com/NASA-AMMOS/MMGIS/assets/2343076/0e003d10-deac-4082-b836-32fb86210483">

**Comment by tariqksoliman** [comment]
Thanks! I should've caught that one. I'm going to merge this all now too.
